services:
  - type: web
    name: ai-past-question-analyzer
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GEMINI_API_KEY
        value: your_api_key_here